### PR TITLE
New Bounty to add missing endpoints to the Lab

### PR DESCRIPTION
**Pull request by w00kie**
As requested on Stellar Quest discord by @tyvdh

See issue #155

### CODE REVIEW

**Review by LorDDark6660 — APPROVED** [review]
it looks good

**Comment by silence48** [comment]
it looks good to me.

**Review by silence48 — CHANGES_REQUESTED** [review]
Let's delete the comment on line [8 ](https://github.com/tyvdh/stellar-quest-bounties/blob/ad3a03129b95084d8699895b029ffb2cbd312cd5/bounties/level-1/add-missing-endpoints-to-lab.md#L8) 
also let's define the range of awards, and also if possible we could include some other targets for endpoints than only fee's.

**Comment by w00kie** [comment]
> and also if possible we could include some other targets for endpoints than only fee's.

Fee Stats is just one suggestion for an easy obvious one. I would argue that digging through the endpoint explorer and the horizon docs to find other missing features is part of the bounty itself.

**Comment by silence48** [comment]
I did actually find some others that could be updated.. automatic fee
bumping to transaction builder would be good. I will try to remember to
make some suggestions tomorrow.  I did the fee bounty that was too easy lol.

**Pull request merged**
