### PR TITLE
Create Proposal for Tipbot

### PR DESCRIPTION
**Pull request by MatejMecka**

### CODE REVIEW

**Comment by tyvdh** [comment]
I love this idea but I'd like to really rethink the structure for simplicity and innovation.

I want all tips to only be a custom emoji asset (e.g. `0x0001F43B => 🐻`) which can be swapped for swag or maybe USDC / XLM at some later date. The point at first should be clout points not monetary incentive points. This is a verifiably better solution as proved time and time again in other more established tipping systems. Think reddit moons/bricks or really the entire "like" model in social media. It's a social token first and a monetary token secondarily, at least for now.

I would love if this could actually be tied to emoji reactions vs running an actual command. It's much easier and more intuitive to react with an emoji than to type out a whole command. We could allow for both or maybe the emoji is a trigger for entering an amount but my default MVP idea would be to just tip a single 🐻  

Ultimately I want this to be simple and fun and not feel like a transaction or payment. It needs to be easy and convenient. I'm even thinking this perhaps shouldn't involve people signing transactions but could actually be a backend system we run just giving out 🐻  or heck any emoji asset sort of like how SQ assets work. So rather than p2p tip payments this would just be a backend service which users can use to mint and pay other users from our accounts. A smart contract vending machine of sorts.

Alternatively we could use a service like lobstr vault to send push notifications for signing and submitting vs reviewing each tip request in Albedo. Just a simple swipe.

Again, innovation and deeper thinking will be needed here but I think its an opportunity to do something different, interesting and actually useful with Stellar tech. Get creative just keep it dead simple user friendly without much intrusion. Enhance the experience, don't add to the experience necessarily if that makes sense.

**Review by silence48 — CHANGES_REQUESTED** [review]
This is a great bounty i think for level 2 bounty.  Could you change your commit to be in [the format of the bounty template](https://github.com/tyvdh/stellar-quest-bounties/tree/main/bounties#bounty-template), and put the changes into the location [/bounties/level2/create_tip_bot.md](https://github.com/tyvdh/stellar-quest-bounties/tree/main/bounties/level-2) ? Thanks! Since this PR is 6 months old, if @MatejMecka is unavailable, I will create a PR for this to go there next week; want to give you a chance to make the pull as it is eligible for the bounty for creating the bounty!

**Review by silence48 — APPROVED** [review]
I like it.  I especially like the bear emojis 👍 maybe someone should contact gnaw bears as this seems to be a good fit :)

**Comment by ElliotFriend** [comment]
Looks like a bunch of fun to me! @MatejMecka If you're ready to say this is complete, will you create an issue for this PR, and I can get your bounty payout prepared?

**Comment by LorDDark6660** [comment]
Nice work Matej...

**Pull request merged**
