### PR TITLE
Add bounty for bounty submissions voting

### PR DESCRIPTION
**Pull request by ralphilius**

### CODE REVIEW

**Comment by Smephite** [comment]
As per Discussion in Discord:

* For each running bounty hunt have a issue tracking it.  
* If a user is to work on a solution to that bounty he should create a _draft_ PR adding his proof of work to the bounty markdown file (headline submissions or similar) linking the tracking issue.
   * This links the issue to the PR thus creating visibility
   * Additional benefit: Peers interested in working on this bounty have an overview over how many competitors are out there. 
* After task completion the PR should be switched to "normal" mode.
* This PR shall be used to discuss and review the submission.
* Reviewers are able to use standard merge request functionality in order to display their approval.
* If enough reviews are accumulated mark task as complete. (--> merge the PR?)
* After the bounty timeframe has ended do payout. 
  * If a voting is needed to find best solution(s) the tracking issue could be used to archive this. (e.g. write comment for every submission, vote via emojis or similar)

To have a bit more of an idea look here at an crude role play of me pretending to be a bot...
https://github.com/SmephiteOrg/stellar-quest-bounties (look at the issues and PRs)

**Comment by Smephite** [comment]
Automation could come in:
* Use GitHub actions to automatically create tracking issue upon bounty.md file creation (push to master event)
  * Automatically add corresponding label
* Bot could track linked PRs and update tracking issue to display number of competitors.
* Upon PR creation bot could automatically assign correct label. (Maybe check if the file edited matches the issue linked).
* Upon PR review bot could check if user has sufficient rank (jr, sr) to review given label
  * if not somehow complain 
  * if yes check if required amount of reviewers have approved and mark the PR as completed (in order to receive admin review or to automatically merge)
  * If submission voting is required use bot to check result (check for duplicates and for required permission)

**Comment by tyvdh** [comment]
This is another great idea but I'd like to wait on it for now while we continue to stabilize the flow a bit more manually. I don't want to spend too much time building for the potentially wrong or half baked ideas.

Once we're a little more set into how the flow should work we can add both automation and the details around how voting could / should work.

Great thoughts and initiative though! Will definitely keep this around for now as a todo item.

**Comment by tyvdh** [comment]
I'm going to close this for now as we'll be using Discussions as a crude voting system for potential bounties for now.
https://github.com/tyvdh/stellar-quest-bounties/discussions

If future demand requires more official support around submission voting we can revisit. Thanks for the great suggestion though! Keep them coming!

Also feel free to disagree and we can revisit.

**Pull request closed without merging**
