### PR TITLE
Add tasklist to issue-template

### PR DESCRIPTION
**Pull request by hanseartic**
This task list allows in the first step poeple to easily see what colors to update their issues' title to. 

Maybe even in a next step the update of the title could be automated with gh bot (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment).

### CODE REVIEW

**Comment by tyvdh** [comment]
I think we'll use the issue template form for this.
https://github.com/tyvdh/stellar-quest-bounties/commit/6dc22a07ba252ea41b49f86ab4217dfa214387d6

Thoughts?

**Comment by hanseartic** [comment]
> Thoughts?

The form allows just for initial creation of the issue, which is perfectly fine and a great help. But once the issue was created the first comment on the issue will be what you'd fill in the form's text-field.

When entering (or prefilling from the template for that matter) in the form:
grafik

the resulting issue would look like this:
grafik

Now the tasklist would allow the hunter to just easily check the checkboxes (no need to go into edit-mode) to mark their progress. You'd even see the progress in the issue's overview:
grafik

And with a bit of bot-magic the 'traffic-light' indicators in the issue-title also could be automatically updated accordingly.

So I'd really like to see the issue-form and the template being combined ;).

**Comment by tyvdh** [comment]
Hmm I think we need to go an either or route but not both. Either you tick the boxes in the issue which translates to a label being updated automatically via a github action (entirely doing away with the emoji prefix) or we just have folks change the title of their issue manually with no checkboxes in the issue itself. The task list is cool looking but doesn't help filter issues at all so it just adds duplicate work for the hunter.

So I think until we have a PR for a github action we stick with only prefix titles.

The checkboxes are really nice though and once hooked up to github actions and labels I think we have a super clean and obvious flow.

**Comment by hanseartic** [comment]
> but doesn't help filter issues at all so it just adds duplicate work for the hunter.

A github-action could *also* update the title (i.e. change the colore-bubble prefix). I'll look into this. So which one would you prefer: labels or color-emoji prefix?

**Comment by tyvdh** [comment]
Labels no doubt. I'd prefer labels in the first place but users can't directly add or modify labels. If we can do that via the task list 👍👍

**Comment by hanseartic** [comment]
> Labels no doubt. I'd prefer labels in the first place but users can't directly add or modify labels. If we can do that via the task list 👍👍

There you go: #84

**Pull request closed without merging**
