### PR TITLE
Add proposal for Tangem XDR Signer

### PR DESCRIPTION
**Pull request by MatejMecka**

### CODE REVIEW

**Comment by Smephite** [comment]
The file looks good to me, maybe the reward is a little low considering current XLM pricing?
Does someone else have some input about that?

**Comment by tyvdh** [comment]
> The file looks good to me, maybe the reward is a little low considering current XLM pricing? Does someone else have some input about that?

Agreed. 3,500 and 1,500 seem more appropriate.

**Comment by silence48** [comment]
> The file looks good to me, maybe the reward is a little low considering current XLM pricing? Does someone else have some input about that?
looks solid to me also.  I too think the reward could be boosted a bit as this is a decent amount of work.  like the wireframe with the bounty!

**Review by silence48 — CHANGES_REQUESTED** [review]
raise reward to 3500 / 1500

**Review by silence48 — APPROVED** [review]

**Review by Smephite — APPROVED** [review]

**Pull request merged**
